### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Hey @hhuijser 

BChan was very insistent on keeping the MFA prefix in the classes, why do we want to remove it only in some (like the _MVCActionCommand_ classes that you've sent)? I understand that it would lose consistency with the rest of the modules.

Thanks!

**Comment by hhuijser** [comment]
@martamedio, correct, if you check other modules, that's the way things are mostly

For example, most classes in the  `document-library-web` have the 'DL` prefix, but the action classes do not have the prefix: https://github.com/liferay/liferay-portal/tree/master/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/action

The idea is that the `mvc.command.name` would have the name of the portlet, so it's clear enough

**Comment by hhuijser** [comment]
And if you just accuse Brian of being inconsistent, he'll agree with whatever you tell him :)

**Comment by arthurchan35** [comment]
https://github.com/hhuijser/liferay-portal/pull/5088

**Pull request closed without merging**
