### PR TITLE
LPS-132439 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-132439

### CODE REVIEW

**Comment by kyle-miho** [comment]
Around 1 out of every 20 runs, this test that you created on CI will randomly spike to a runtime of around ~ 10500ms and causes a random failure. Since I saw that this has happened in the past before (I checked the git log, I assume that this a similar issue)

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/371

**Comment by arthurchan35** [comment]
@kyle-miho 
Forgot to mention, for furture pull requests, please send to 
https://github.com/liferay-appsec/liferay-portal

Best Regards,
Arthur

**Pull request closed without merging**
