### PR TITLE
Lps 150092 alternative

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:oidc

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:oidc

**Comment by arthurchan35** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
All the OIDC functional testcases passed on PR#183:
https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1898683136&testrayCaseTypeId=101949

The failure of [central-requirements-jdk8/0/0](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/99494/) is not related to the current PR.

**Comment by arthurchan35** [comment]
Use liferay-appsec for this task:
https://github.com/liferay-appsec/liferay-portal/pull/736

**Pull request closed without merging**
