### PR TITLE
Use UpgradeStepFactory pattern

### PR DESCRIPTION
**Pull request by csierra**
hey @arthurchan35, 

I leave this here as an example for later because I think we should better use the UpgradeStepFactory pattern. I did not want to send the commit yesterday to not have to run the CI again (and it took very long), but maybe Brian is going to tell us to use this or we can send it once it is merged. 

Have a look at OAuth2 upgrades for more examples. 

Bests. 

Carlos.

### CODE REVIEW

**Comment by arthurchan35** [comment]
Ok understood, thanks @csierra

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
but no need to forward it now... I don't know if Brian would like to have this in a private method and I would not update the UpgradeStepFactory now

**Pull request closed without merging**
