### PR TITLE
Lps 150092 full

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:upgrade

**Comment by JoyceWang08211** [comment]
Bug:
1. Navigate to System Settings > SSO > OpenID Connect Provider Connection
2. Add a configuration entry. e.g. Google
3. Navigate to Instance Settings > SSO > OpenID Connect
4. Check enabled
5. Sign out
6. Click “Sign In”

Expected result: “OpenID Connect” option should show up.

Actual result: “OpenID Connect” option doesn't show up.

cc @arthurchan35 and @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
Failures of ci:test:upgrade are caused by LRQA-75846 and LPS-129558. Not related to the current PR.

cc @arthurchan35 and @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
> Bug:
> 
> 1. Navigate to System Settings > SSO > OpenID Connect Provider Connection
> 2. Add a configuration entry. e.g. Google
> 3. Navigate to Instance Settings > SSO > OpenID Connect
> 4. Check enabled
> 5. Sign out
> 6. Click “Sign In”
> 
> **Actual result:** “OpenID Connect” option doesn't show up.
> 
> **Expected result:** “OpenID Connect” option should show up. expected result
> 
> cc @arthurchan35 and @gaborlovasdotcom

After confirmed with Arthur, the above failure is due to missing OAuth client configuration. Nevertheless, there is something wrong when I configured OAuth client.

@gaborlovasdotcom Could you please help double checking this issue? Here is the steps:
Scenario 1：
1. Navigate to OAuth Client Administration
2. Add a configuration entry as following:
**OAuth Client Information：**
{
    "client_id": "[626781307908-0ppoijm0lmbqbetujj5lqu5gkqu9onh7.apps.googleusercontent.com](http://626781307908-0ppoijm0lmbqbetujj5lqu5gkqu9onh7.apps.googleusercontent.com/)",
    "client_secret": "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",
    "redirect_uris": [
        ""
    ],
    "client_name": "Google",
    "scope": "openid email profile",
    "subject_type": "public",
    "grant_types": [
        "authorization_code",
        "refresh_token"
    ],
    "response_types": [
        "code"
    ]
}
**OAuth Client Default Authorization Request Parameters：**
{
    "response_type": "code",
    "scope": "openid email profile"
}
**OAuth Client Default Token Request Parameters：**
{
    "grant_type": "authorization_code",
    "scope": "openid email profile"
}
3. Navigate to Instance Settings > SSO > OpenID Connect
4. Check enabled
5. Sign out
6. Click “Sign In”
7. Click “OpenID Connect”
8. Login using a valid Google account

Scenario 2：
1. Navigate to OAuth Client Administration
2. Add a configuration entry as above.
3. Click Save
4. Delete the new added configuration entry.
5. Readd the configuration entry as above.
6. Navigate to Instance Settings > SSO > OpenID Connect
7. Check enabled
8. Sign out
9. Click “Sign In”
10. Click “OpenID Connect”
11. Login using a valid Google account

**Comment by arthurchan35** [comment]
I just did an ant all using this PR rebased on latest master, and I am able to add this configuration.

I suspect it was because I added some other service code that was merged into master while this PR did not have.

I have rebase this PR to the latest master.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:upgrade

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
> @gaborlovasdotcom @JoyceWang08211
> Hi, I am pretty there are tests needing updating, because, with this story, the OIDC configurations are no longer used, and are replaced with OAuth client admin web.

@JoyceWang08211 Based on this new feature the bug is not applicable here. I tested it and both scenarios worked for me on the recent [bundle](https://github.com/arthurchan35/liferay-portal/pull/178#issuecomment-1169707640) after the rebase.
@arthurchan35 Yes we need to update the tests as the configuration didn't read up from the old: Instance Settings / SSO / OpenID Connect Provider Connection menu

**Comment by JoyceWang08211** [comment]
> > @gaborlovasdotcom @JoyceWang08211
> > Hi, I am pretty there are tests needing updating, because, with this story, the OIDC configurations are no longer used, and are replaced with OAuth client admin web.
> 
> @JoyceWang08211 Based on this new feature the bug is not applicable here. I tested it and both scenarios worked for me on the recent [bundle](https://github.com/arthurchan35/liferay-portal/pull/178#issuecomment-1169707640) after the rebase. @arthurchan35 Yes we need to update the tests as the configuration didn't read up from the old: Instance Settings / SSO / OpenID Connect Provider Connection menu

@gaborlovasdotcom Thanks for the double checking, I'll update the related testcases in LPS-157203 and commit to the feature branch, aka [LPS-150092-full](https://github.com/liferay-appsec/liferay-portal/tree/LPS-150092-full)

cc @arthurchan35

**Comment by arthurchan35** [comment]
See:
https://github.com/arthurchan35/liferay-portal/pull/179

**Pull request closed without merging**
