### PR TITLE
LPS-111617 SF better readability

### PR DESCRIPTION
**Pull request by csierra**
hey @arthurchan35, 

this is a new pull with all tests passing after your review. 

If you are ok with the changes we can try and send it to merge.

Thx. 

Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@csierra,
Changes look good to me, let's try to forward this pull.

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
