### PR TITLE
LPS-113348 Add CORS tests using Basic and Portal Session

### PR DESCRIPTION
**Pull request by martamedio**
Hey @arthurchan35 👋 

Please, take a look at the CORS changes included in this PR taking into account:
- It's been decided that CORS should only apply if it's the request is a valid OAuth2 request
- Different request test cases have been added that were not covered (if you can think of any more cases to check, please, let me know!)

Thanks!

cc/ @csierra

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Ops! Looks like `CORSConfigurationPortalTest.testNoCORSUsingPortalSession` needs a second review 👀

**Comment by arthurchan35** [comment]
@martamedio ,
The changes seem not to conflict with what I have been writing, once your changes are merged, it's only a matter of another if check to my code.

Thanks for letting me know!

Arthur

**Pull request closed without merging**
